import os,time
from instaclient import InstaClient
from instaclient.errors import *

#print(str(os.getcwd())+"/var/chromedriver")
#->/home/zhaba/Public/github/InstaParser/var/chromedriver
#Also run it: /home/zhaba/Public/github/InstaParser/var/chromedriver
#client = InstaClient("/home/zhaba/Public/github/InstaParser/var/chromedriver")


print("/home/zhaba/Desktop/chromedriver:")
print(os.path.isfile("/home/zhaba/Desktop/chromedriver"))

print(os.getcwd()+"var/chromedriver:")
print(os.path.isfile(os.getcwd()+"var/chromedriver"))

print("/home/zhaba/Public/github/InstaParser/var/chromedriver")
print(os.path.isfile("/home/zhaba/Public/github/InstaParser/var/chromedriver"))


#/home/zhaba/Desktop/chromedriver:
#True
#/home/zhaba/Public/github/InstaParservar/chromedriver:
#False
#/home/zhaba/Public/github/InstaParser/var/chromedriver
#True


def connect(username,pwd):
  client = InstaClient("/home/zhaba/Desktop/chromedriver")
  try:
    client.login(username=username, password=pwd)
  except VerificationCodeNecessary:
    code = input('Enter the 2FA security code generated by your Authenticator App or sent to you by SMS')
    client.input_verification_code(code)
  except SuspisciousLoginAttemptError as error:
    if error.mode == SuspisciousLoginAttemptError.EMAIL:
      code = input('Enter the security code that was sent to you via email: ')
    else:
      code = input('Enter the security code that was sent to you via SMS: ')
  client.input_security_code(code)

#connect("sdf","asfasdfsaf")
